%% ================================================================
% CMM TTC FINAL TIRE CHARACTERIZATION v1.5
%
% PURPOSE
%   Final engineering characterization of the TTC lateral tire data
%   before Magic Formula / Pacejka fitting.
%
% INPUT
%   TTC_CONDITION_ASSIGNED_DATABASE.csv
%   generated by v1.3
%
% OUTPUT
%   - Load-binned peak Fy
%   - Load-binned mu_y
%   - Peak slip angle
%   - Cornering stiffness
%   - Positive / negative SA comparison
%   - Symmetry analysis
%   - Pressure sensitivity
%   - Camber sensitivity
%   - Reference-condition characterization
%   - Engineering plots
%   - Team report
%
% IMPORTANT
%   NO Pacejka fitting is performed here.
%
% ================================================================

clear;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' CMM TTC FINAL TIRE CHARACTERIZATION v1.5\n');
fprintf('============================================================\n\n');

%% ================================================================
% 1. USER SETTINGS
% ================================================================

% ------------------------------------------------
% Reference condition
% ------------------------------------------------

REF_PRESSURE_PSI = 12.09;
REF_PRESSURE_KPA = REF_PRESSURE_PSI / 0.1450377;

REF_CAMBER_DEG = 0.0;
REF_SPEED_KPH = 40.22;

REF_FZ_N = 871.5;

% Reference tolerances
REF_PRESSURE_TOL_PSI = 0.25;
REF_CAMBER_TOL_DEG   = 0.25;
REF_FZ_TOL_N          = 75;

% ------------------------------------------------
% Load analysis
% ------------------------------------------------

MIN_ANALYSIS_FZ = 300;
MAX_ANALYSIS_FZ = 1200;

LOAD_BIN_WIDTH = 100;

MIN_BIN_SAMPLES = 50;

% ------------------------------------------------
% Peak extraction
% ------------------------------------------------

FY_SMOOTH_WINDOW = 21;

% Minimum SA magnitude for a valid peak
MIN_PEAK_SA_DEG = 3.0;

% ------------------------------------------------
% Cornering stiffness
% ------------------------------------------------

CA_LIMIT_DEG = 2.0;

% ------------------------------------------------
% Low-load warning
% ------------------------------------------------

LOW_LOAD_LIMIT = 300;

% ------------------------------------------------
% Symmetry
% ------------------------------------------------

SYMMETRY_SA_LIMIT = 10;

%% ================================================================
% 2. SELECT PROJECT
% ================================================================

fprintf('[1] SELECT CMM PROJECT FOLDER\n');
fprintf('------------------------------------------------------------\n');

projectFolder = uigetdir(pwd,...
    'Select CMM / TTC project folder');

if isequal(projectFolder,0)
    error('No project folder selected.');
end

fprintf('Selected folder:\n%s\n\n',projectFolder);

%% ================================================================
% 3. LOCATE v1.3 DATABASE
% ================================================================

fprintf('[2] LOCATING CONDITION DATABASE\n');
fprintf('------------------------------------------------------------\n');

dbFile = fullfile(...
    projectFolder,...
    '_PRE_MF_MATRIX_v1_3',...
    'TTC_CONDITION_ASSIGNED_DATABASE.csv');

if ~isfile(dbFile)

    error(['v1.3 condition database not found:\n\n%s\n\n',...
           'Run v1.3 first.'],dbFile);

end

fprintf('Database:\n%s\n\n',dbFile);

%% ================================================================
% 4. OUTPUT FOLDER
% ================================================================

thisFile = mfilename('fullpath');
repoRoot = fileparts(fileparts(thisFile));
outputFolder = fullfile(repoRoot,'outputs','08_PRE_MF_FINAL_v1_5');

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

fprintf('Output folder:\n%s\n\n',outputFolder);

%% ================================================================
% 5. LOAD DATABASE
% ================================================================

fprintf('[3] LOADING CONDITION DATABASE\n');
fprintf('------------------------------------------------------------\n');

D = readtable(dbFile);

fprintf('Rows loaded : %d\n',height(D));

%% ================================================================
% 6. REQUIRED VARIABLES
% ================================================================

requiredVars = {...
    'ET',...
    'SA_deg',...
    'FY_N',...
    'FZ_N',...
    'IA_deg',...
    'Pressure_kPa',...
    'Speed_kph',...
    'PressureState',...
    'CamberState',...
    'Camber_deg',...
    'ConditionID'};

for k = 1:numel(requiredVars)

    if ~ismember(requiredVars{k},D.Properties.VariableNames)

        error('Missing variable: %s',requiredVars{k});

    end

end

%% ================================================================
% 7. BASIC QC
% ================================================================

fprintf('\n[4] SIGNAL QUALITY CONTROL\n');
fprintf('------------------------------------------------------------\n');

valid = ...
    isfinite(D.ET) & ...
    isfinite(D.SA_deg) & ...
    isfinite(D.FY_N) & ...
    isfinite(D.FZ_N) & ...
    isfinite(D.IA_deg) & ...
    isfinite(D.Pressure_kPa) & ...
    isfinite(D.Speed_kph);

invalidCount = sum(~valid);

D = D(valid,:);

fprintf('Valid samples   : %d\n',height(D));
fprintf('Invalid samples : %d\n',invalidCount);

fprintf('\nSignal ranges:\n');

fprintf('SA : %.3f to %.3f deg\n',...
    min(D.SA_deg),max(D.SA_deg));

fprintf('FY : %.2f to %.2f N\n',...
    min(D.FY_N),max(D.FY_N));

fprintf('FZ : %.2f to %.2f N\n',...
    min(D.FZ_N),max(D.FZ_N));

%% ================================================================
% 8. IDENTIFY CONDITIONS
% ================================================================

conditionIDs = unique(D.ConditionID);

fprintf('\n[5] TEST CONDITIONS\n');
fprintf('------------------------------------------------------------\n');

fprintf('Conditions found : %d\n',numel(conditionIDs));

for k = 1:numel(conditionIDs)

    mask = D.ConditionID == conditionIDs(k);

    fprintf(...
        'Condition %d : P = %.2f psi | IA = %+5.2f deg | N = %d\n',...
        conditionIDs(k),...
        median(D.Pressure_kPa(mask))*0.1450377,...
        median(D.Camber_deg(mask)),...
        sum(mask));

end

%% ================================================================
% 9. LOAD BINS
% ================================================================

loadEdges = ...
    MIN_ANALYSIS_FZ:LOAD_BIN_WIDTH:MAX_ANALYSIS_FZ;

loadCenters = ...
    loadEdges(1:end-1) + LOAD_BIN_WIDTH/2;

nBins = numel(loadCenters);

%% ================================================================
% 10. RESULT ARRAYS
% ================================================================

ConditionResults = struct([]);

MasterCondition = [];
MasterPressure = [];
MasterCamber = [];
MasterFZ = [];

MasterPeakFY = [];
MasterPeakSA = [];
MasterMu = [];

MasterPeakFY_Pos = [];
MasterPeakFY_Neg = [];

MasterSA_Pos = [];
MasterSA_Neg = [];

MasterMu_Pos = [];
MasterMu_Neg = [];

MasterCA = [];

MasterSamples = [];

%% ================================================================
% 11. CONDITION ANALYSIS
% ================================================================

fprintf('\n[6] CONDITION-BY-CONDITION CHARACTERIZATION\n');
fprintf('============================================================\n');

for c = 1:numel(conditionIDs)

    cid = conditionIDs(c);

    conditionMask = ...
        D.ConditionID == cid;

    T = D(conditionMask,:);

    if height(T) < 100
        continue;
    end

    pressureKPa = median(T.Pressure_kPa,'omitnan');
    pressurePsi = pressureKPa*0.1450377;

    camberDeg = median(T.Camber_deg,'omitnan');

    fprintf('\n------------------------------------------------------------\n');
    fprintf('CONDITION %d\n',cid);
    fprintf('Pressure : %.2f psi\n',pressurePsi);
    fprintf('Camber   : %+5.2f deg\n',camberDeg);
    fprintf('Samples  : %d\n',height(T));

    %% ------------------------------------------------------------
    % Sort by elapsed time
    % ------------------------------------------------------------

    [~,order] = sort(T.ET);

    T = T(order,:);

    %% ------------------------------------------------------------
    % Smooth force for peak detection
    % ------------------------------------------------------------

    FYsmooth = movmean(...
        T.FY_N,...
        FY_SMOOTH_WINDOW);

    %% ------------------------------------------------------------
    % Allocate
    % ------------------------------------------------------------

    peakFY = nan(nBins,1);
    peakSA = nan(nBins,1);
    peakFZ = nan(nBins,1);
    mu = nan(nBins,1);

    peakFYpos = nan(nBins,1);
    peakFYneg = nan(nBins,1);

    peakSApos = nan(nBins,1);
    peakSAneg = nan(nBins,1);

    muPos = nan(nBins,1);
    muNeg = nan(nBins,1);

    CAlpha = nan(nBins,1);

    binSamples = zeros(nBins,1);

    %% ------------------------------------------------------------
    % LOAD BINS
    % ------------------------------------------------------------

    for b = 1:nBins

        lowFZ = loadEdges(b);
        highFZ = loadEdges(b+1);

        maskBin = ...
            T.FZ_N >= lowFZ & ...
            T.FZ_N < highFZ;

        if sum(maskBin) < MIN_BIN_SAMPLES
            continue;
        end

        fz = T.FZ_N(maskBin);
        sa = T.SA_deg(maskBin);
        fy = FYsmooth(maskBin);

        binSamples(b) = sum(maskBin);

        %% --------------------------------------------------------
        % POSITIVE SLIP SIDE
        % --------------------------------------------------------

        posMask = sa >= MIN_PEAK_SA_DEG;

        if sum(posMask) >= 10

            fyPos = fy(posMask);
            saPos = sa(posMask);
            fzPos = fz(posMask);

            [pkPos,idxPos] = max(abs(fyPos));

            peakFYpos(b) = pkPos;
            peakSApos(b) = saPos(idxPos);

            localFZ = fzPos(idxPos);

            muPos(b) = pkPos/max(localFZ,eps);

        end

        %% --------------------------------------------------------
        % NEGATIVE SLIP SIDE
        % --------------------------------------------------------

        negMask = sa <= -MIN_PEAK_SA_DEG;

        if sum(negMask) >= 10

            fyNeg = fy(negMask);
            saNeg = sa(negMask);
            fzNeg = fz(negMask);

            [pkNeg,idxNeg] = max(abs(fyNeg));

            peakFYneg(b) = pkNeg;
            peakSAneg(b) = saNeg(idxNeg);

            localFZ = fzNeg(idxNeg);

            muNeg(b) = pkNeg/max(localFZ,eps);

        end

        %% --------------------------------------------------------
        % COMBINED PEAK
        % --------------------------------------------------------

        [pkAll,idxAll] = max(abs(fy));

        peakFY(b) = pkAll;

        peakSA(b) = sa(idxAll);

        peakFZ(b) = fz(idxAll);

        mu(b) = pkAll/max(peakFZ(b),eps);

        %% --------------------------------------------------------
        % CORNERING STIFFNESS
        % --------------------------------------------------------

        caMask = abs(sa)<=CA_LIMIT_DEG;

        if sum(caMask)>=20

            x = sa(caMask);
            y = fy(caMask);

            % Remove duplicate slip-angle values safely
            [xUnique,~,group] = unique(x);

            yUnique = accumarray(...
                group,...
                y,...
                [],...
                @mean);

            if numel(xUnique)>=5

                % Local linear fit
                pp = polyfit(...
                    xUnique,...
                    yUnique,...
                    1);

                CAlpha(b) = abs(pp(1));

            end

        end

    end

    %% ============================================================
    % STORE CONDITION
    % ============================================================

    ConditionResults(c).ConditionID = cid;
    ConditionResults(c).PressurePsi = pressurePsi;
    ConditionResults(c).PressureKPa = pressureKPa;
    ConditionResults(c).CamberDeg = camberDeg;

    ConditionResults(c).LoadCenters = loadCenters(:);

    ConditionResults(c).PeakFY = peakFY;
    ConditionResults(c).PeakFZ = peakFZ;
    ConditionResults(c).PeakSA = peakSA;
    ConditionResults(c).Mu = mu;

    ConditionResults(c).PeakFY_Pos = peakFYpos;
    ConditionResults(c).PeakFY_Neg = peakFYneg;

    ConditionResults(c).PeakSA_Pos = peakSApos;
    ConditionResults(c).PeakSA_Neg = peakSAneg;

    ConditionResults(c).Mu_Pos = muPos;
    ConditionResults(c).Mu_Neg = muNeg;

    ConditionResults(c).CAlpha = CAlpha;
    ConditionResults(c).Samples = binSamples;

    %% ============================================================
    % APPEND MASTER TABLE
    % ============================================================

    good = ...
        isfinite(peakFZ) & ...
        isfinite(mu);

    MasterCondition = [MasterCondition; ...
        repmat(cid,sum(good),1)];

    MasterPressure = [MasterPressure; ...
        repmat(pressurePsi,sum(good),1)];

    MasterCamber = [MasterCamber; ...
        repmat(camberDeg,sum(good),1)];

    MasterFZ = [MasterFZ; ...
        peakFZ(good)];

    MasterPeakFY = [MasterPeakFY; ...
        peakFY(good)];

    MasterPeakSA = [MasterPeakSA; ...
        peakSA(good)];

    MasterMu = [MasterMu; ...
        mu(good)];

    MasterPeakFY_Pos = [MasterPeakFY_Pos; ...
        peakFYpos(good)];

    MasterPeakFY_Neg = [MasterPeakFY_Neg; ...
        peakFYneg(good)];

    MasterSA_Pos = [MasterSA_Pos; ...
        peakSApos(good)];

    MasterSA_Neg = [MasterSA_Neg; ...
        peakSAneg(good)];

    MasterMu_Pos = [MasterMu_Pos; ...
        muPos(good)];

    MasterMu_Neg = [MasterMu_Neg; ...
        muNeg(good)];

    MasterCA = [MasterCA; ...
        CAlpha(good)];

    MasterSamples = [MasterSamples; ...
        binSamples(good)];

    fprintf('Valid load bins : %d / %d\n',...
        sum(good),nBins);

end

%% ================================================================
% 12. MASTER TABLE
% ================================================================

MASTER = table(...
    MasterCondition,...
    MasterPressure,...
    MasterCamber,...
    MasterFZ,...
    MasterPeakFY,...
    MasterMu,...
    MasterPeakSA,...
    MasterPeakFY_Pos,...
    MasterPeakFY_Neg,...
    MasterSA_Pos,...
    MasterSA_Neg,...
    MasterMu_Pos,...
    MasterMu_Neg,...
    MasterCA,...
    MasterSamples,...
    'VariableNames',{...
    'ConditionID',...
    'Pressure_psi',...
    'Camber_deg',...
    'FZ_N',...
    'PeakFY_N',...
    'Mu_y',...
    'PeakSA_deg',...
    'PeakFY_Pos_N',...
    'PeakFY_Neg_N',...
    'PeakSA_Pos_deg',...
    'PeakSA_Neg_deg',...
    'Mu_Pos',...
    'Mu_Neg',...
    'CAlpha_NperDeg',...
    'Samples'});

%% ================================================================
% 13. SAVE MASTER CSV
% ================================================================

masterCSV = fullfile(...
    outputFolder,...
    'TIRE_CHARACTERIZATION_MASTER_v1_5.csv');

writetable(MASTER,masterCSV);

fprintf('\n[7] MASTER CHARACTERIZATION\n');
fprintf('------------------------------------------------------------\n');
fprintf('Rows : %d\n',height(MASTER));
fprintf('Saved:\n%s\n',masterCSV);

%% ================================================================
% 14. REFERENCE CONDITION
% ================================================================

fprintf('\n[8] REFERENCE CONDITION\n');
fprintf('------------------------------------------------------------\n');

refMask = ...
    abs(MASTER.Pressure_psi-REF_PRESSURE_PSI) ...
        <= REF_PRESSURE_TOL_PSI & ...
    abs(MASTER.Camber_deg-REF_CAMBER_DEG) ...
        <= REF_CAMBER_TOL_DEG & ...
    abs(MASTER.FZ_N-REF_FZ_N) ...
        <= REF_FZ_TOL_N;

REF = MASTER(refMask,:);

if isempty(REF)

    fprintf('WARNING: No reference bins found.\n');

    refMedianMu = NaN;
    refMeanMu = NaN;
    refMaxMu = NaN;
    refMedianCA = NaN;
    refMedianPeakSA = NaN;
    refMedianFY = NaN;

else

    refMedianMu = median(REF.Mu_y,'omitnan');

    refMeanMu = mean(REF.Mu_y,'omitnan');

    refMaxMu = max(REF.Mu_y);

    refMedianCA = median(...
        REF.CAlpha_NperDeg,...
        'omitnan');

    refMedianPeakSA = median(...
        abs(REF.PeakSA_deg),...
        'omitnan');

    refMedianFY = median(...
        REF.PeakFY_N,...
        'omitnan');

    fprintf('Pressure       : %.2f psi\n',REF_PRESSURE_PSI);
    fprintf('Camber         : %.2f deg\n',REF_CAMBER_DEG);
    fprintf('Reference FZ   : %.1f N\n',REF_FZ_N);

    fprintf('\nBins found     : %d\n',height(REF));

    fprintf('Median mu_y    : %.4f\n',refMedianMu);
    fprintf('Mean mu_y      : %.4f\n',refMeanMu);
    fprintf('Maximum mu_y   : %.4f\n',refMaxMu);

    fprintf('Median C-alpha : %.3f N/deg\n',refMedianCA);
    fprintf('Median peak SA : %.3f deg\n',refMedianPeakSA);
    fprintf('Median peak FY : %.2f N\n',refMedianFY);

end

%% ================================================================
% 15. GLOBAL LOAD-BINNED MAXIMUM
% ================================================================

fprintf('\n[9] GLOBAL LOAD-BINNED RESULT\n');
fprintf('------------------------------------------------------------\n');

[globalMu,idxGlobal] = max(MASTER.Mu_y);

fprintf('Maximum binned mu : %.4f\n',globalMu);

fprintf('Pressure          : %.2f psi\n',...
    MASTER.Pressure_psi(idxGlobal));

fprintf('Camber            : %+5.2f deg\n',...
    MASTER.Camber_deg(idxGlobal));

fprintf('FZ                : %.2f N\n',...
    MASTER.FZ_N(idxGlobal));

fprintf('FY                : %.2f N\n',...
    MASTER.PeakFY_N(idxGlobal));

fprintf('SA                : %.2f deg\n',...
    MASTER.PeakSA_deg(idxGlobal));

%% ================================================================
% 16. LOW LOAD CHECK
% ================================================================

fprintf('\n[10] LOW-LOAD MU CHECK\n');
fprintf('------------------------------------------------------------\n');

lowMask = MASTER.FZ_N < LOW_LOAD_LIMIT;

if any(lowMask)

    lowMuMedian = median(...
        MASTER.Mu_y(lowMask),...
        'omitnan');

    lowMuMax = max(...
        MASTER.Mu_y(lowMask));

    fprintf('Low-load bins : %d\n',sum(lowMask));
    fprintf('Median mu     : %.4f\n',lowMuMedian);
    fprintf('Maximum mu    : %.4f\n',lowMuMax);

    fprintf('\nNOTE:\n');
    fprintf(['Low-load mu is retained for audit only and is NOT ',...
        'used as the primary tire coefficient.\n']);

else

    lowMuMedian = NaN;
    lowMuMax = NaN;

    fprintf('No low-load bins available.\n');

end

%% ================================================================
% 17. LEFT / RIGHT SYMMETRY
% ================================================================

fprintf('\n[11] LEFT / RIGHT SYMMETRY\n');
fprintf('------------------------------------------------------------\n');

symmetryRatio = ...
    MASTER.Mu_Pos ./ max(MASTER.Mu_Neg,eps);

symmetryValid = ...
    isfinite(symmetryRatio) & ...
    MASTER.Mu_Pos>0 & ...
    MASTER.Mu_Neg>0;

if any(symmetryValid)

    medianSymmetry = median(...
        symmetryRatio(symmetryValid),...
        'omitnan');

    symmetryStd = std(...
        symmetryRatio(symmetryValid),...
        'omitnan');

    fprintf('Median positive/negative ratio : %.4f\n',...
        medianSymmetry);

    fprintf('Std                          : %.4f\n',...
        symmetryStd);

else

    medianSymmetry = NaN;
    symmetryStd = NaN;

    fprintf('Insufficient symmetry data.\n');

end

%% ================================================================
% 18. DARK PLOT HELPER
% ================================================================

function darkPlot()

    set(gcf,'Color','k');

    ax = gca;

    set(ax,...
        'Color','k',...
        'XColor','w',...
        'YColor','w',...
        'GridColor',[0.45 0.45 0.45],...
        'MinorGridColor',[0.25 0.25 0.25],...
        'GridAlpha',0.35,...
        'MinorGridAlpha',0.2,...
        'FontSize',11,...
        'LineWidth',1);

    grid on;

    ax.XLabel.Color = 'w';
    ax.YLabel.Color = 'w';
    ax.Title.Color = 'w';

end

%% ================================================================
% 19. PLOT 1 - LOAD BINNED MU
% ================================================================

figure('Color','k');

scatter(...
    MASTER.FZ_N,...
    MASTER.Mu_y,...
    42,...
    MASTER.Pressure_psi,...
    'filled');

hold on;

xline(REF_FZ_N,...
    '--w',...
    'Reference F_Z',...
    'LineWidth',1.2);

xlabel('Vertical Load F_Z [N]');
ylabel('\mu_y');

title('Load-Binned Tire Friction');

cb = colorbar;
cb.Color = 'w';
ylabel(cb,'Pressure [psi]','Color','w');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '01_LOAD_BINNED_MU.png'),...
    'Resolution',200);

%% ================================================================
% 20. PLOT 2 - PEAK FY VS FZ
% ================================================================

figure('Color','k');

scatter(...
    MASTER.FZ_N,...
    MASTER.PeakFY_N,...
    42,...
    MASTER.Camber_deg,...
    'filled');

xlabel('Vertical Load F_Z [N]');
ylabel('Peak |F_Y| [N]');

title('Peak Lateral Force vs Vertical Load');

cb = colorbar;
cb.Color = 'w';
ylabel(cb,'Camber [deg]','Color','w');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '02_PEAK_FY_VS_FZ.png'),...
    'Resolution',200);

%% ================================================================
% 21. PLOT 3 - CORNERING STIFFNESS
% ================================================================

figure('Color','k');

scatter(...
    MASTER.FZ_N,...
    MASTER.CAlpha_NperDeg,...
    42,...
    MASTER.Pressure_psi,...
    'filled');

xlabel('Vertical Load F_Z [N]');
ylabel('C_\alpha [N/deg]');

title('Cornering Stiffness vs Vertical Load');

cb = colorbar;
cb.Color = 'w';
ylabel(cb,'Pressure [psi]','Color','w');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '03_CORNERING_STIFFNESS.png'),...
    'Resolution',200);

%% ================================================================
% 22. PLOT 4 - PEAK SLIP ANGLE
% ================================================================

figure('Color','k');

scatter(...
    MASTER.FZ_N,...
    abs(MASTER.PeakSA_deg),...
    42,...
    MASTER.Camber_deg,...
    'filled');

xlabel('Vertical Load F_Z [N]');
ylabel('|Peak Slip Angle| [deg]');

title('Peak Slip Angle vs Vertical Load');

cb = colorbar;
cb.Color = 'w';
ylabel(cb,'Camber [deg]','Color','w');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '04_PEAK_SLIP_ANGLE.png'),...
    'Resolution',200);

%% ================================================================
% 23. PLOT 5 - PRESSURE SENSITIVITY
% ================================================================

figure('Color','k');

hold on;

pressureStates = unique(MASTER.Pressure_psi);

for k = 1:numel(pressureStates)

    mask = ...
        abs(MASTER.Camber_deg)<0.25 & ...
        abs(MASTER.Pressure_psi-pressureStates(k))<0.01;

    if any(mask)

        [xSort,order] = sort(MASTER.FZ_N(mask));

        ySort = MASTER.Mu_y(mask);
        ySort = ySort(order);

        plot(...
            xSort,...
            ySort,...
            'o-',...
            'LineWidth',1.3,...
            'DisplayName',...
            sprintf('%.2f psi',pressureStates(k)));

    end

end

xlabel('Vertical Load F_Z [N]');
ylabel('\mu_y');

title('Pressure Sensitivity at 0° Camber');

legend('TextColor','w',...
       'Color','k',...
       'Location','best');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '05_PRESSURE_SENSITIVITY.png'),...
    'Resolution',200);

%% ================================================================
% 24. PLOT 6 - CAMBER SENSITIVITY
% ================================================================

figure('Color','k');

hold on;

camberStates = unique(MASTER.Camber_deg);

for k = 1:numel(camberStates)

    mask = ...
        abs(MASTER.Pressure_psi-REF_PRESSURE_PSI) ...
            <= REF_PRESSURE_TOL_PSI & ...
        abs(MASTER.Camber_deg-camberStates(k)) ...
            < 0.25;

    if any(mask)

        [xSort,order] = sort(MASTER.FZ_N(mask));

        ySort = MASTER.Mu_y(mask);
        ySort = ySort(order);

        plot(...
            xSort,...
            ySort,...
            'o-',...
            'LineWidth',1.3,...
            'DisplayName',...
            sprintf('%+.0f deg',camberStates(k)));

    end

end

xlabel('Vertical Load F_Z [N]');
ylabel('\mu_y');

title('Camber Sensitivity at ~12.1 psi');

legend('TextColor','w',...
       'Color','k',...
       'Location','best');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '06_CAMBER_SENSITIVITY.png'),...
    'Resolution',200);

%% ================================================================
% 25. PLOT 7 - POSITIVE / NEGATIVE SA
% ================================================================

figure('Color','k');

validSym = ...
    isfinite(MASTER.Mu_Pos) & ...
    isfinite(MASTER.Mu_Neg);

scatter(...
    MASTER.Mu_Pos(validSym),...
    MASTER.Mu_Neg(validSym),...
    42,...
    MASTER.FZ_N(validSym),...
    'filled');

hold on;

lims = [...
    min([MASTER.Mu_Pos(validSym);...
         MASTER.Mu_Neg(validSym)]),...
    max([MASTER.Mu_Pos(validSym);...
         MASTER.Mu_Neg(validSym)])];

plot(lims,lims,'--w','LineWidth',1.2);

xlabel('Positive-SA \mu_y');
ylabel('Negative-SA \mu_y');

title('Positive / Negative Slip Symmetry');

cb = colorbar;
cb.Color = 'w';
ylabel(cb,'F_Z [N]','Color','w');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '07_SA_SYMMETRY.png'),...
    'Resolution',200);

%% ================================================================
% 26. PLOT 8 - REFERENCE FY VS SA
% ================================================================

figure('Color','k');

referenceDataMask = ...
    abs(D.Pressure_kPa-REF_PRESSURE_KPA)<=1.0 & ...
    abs(D.Camber_deg-REF_CAMBER_DEG)<=0.25 & ...
    abs(D.FZ_N-REF_FZ_N)<=REF_FZ_TOL_N;

if sum(referenceDataMask)>=100

    scatter(...
        D.SA_deg(referenceDataMask),...
        D.FY_N(referenceDataMask),...
        8,...
        D.FZ_N(referenceDataMask),...
        'filled');

    xlabel('Slip Angle [deg]');
    ylabel('F_Y [N]');

    title('Reference Condition: F_Y vs Slip Angle');

    cb = colorbar;
    cb.Color = 'w';
    ylabel(cb,'F_Z [N]','Color','w');

else

    text(...
        0.25,...
        0.5,...
        'Insufficient reference-condition data',...
        'Color','w',...
        'FontSize',14);

    axis off;

end

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '08_REFERENCE_FY_SA.png'),...
    'Resolution',200);

%% ================================================================
% 27. PLOT 9 - MU DISTRIBUTION
% ================================================================

figure('Color','k');

histogram(...
    MASTER.Mu_y,...
    25,...
    'FaceAlpha',0.85);

hold on;

if isfinite(refMedianMu)

    xline(...
        refMedianMu,...
        '--w',...
        'Reference median',...
        'LineWidth',1.5);

end

xlabel('\mu_y');
ylabel('Number of load bins');

title('Load-Binned Friction Distribution');

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '09_MU_DISTRIBUTION.png'),...
    'Resolution',200);

%% ================================================================
% 28. PLOT 10 - LOAD SENSITIVITY AT REFERENCE CONDITION
% ================================================================

figure('Color','k');

if ~isempty(REF)

    [xSort,order] = sort(REF.FZ_N);

    ySort = REF.Mu_y(order);

    plot(...
        xSort,...
        ySort,...
        'o-',...
        'LineWidth',1.5,...
        'MarkerSize',6);

    hold on;

    xline(...
        REF_FZ_N,...
        '--w',...
        'Reference F_Z',...
        'LineWidth',1.2);

    xlabel('Vertical Load F_Z [N]');
    ylabel('\mu_y');

    title('Reference Tire Load Sensitivity');

else

    text(...
        0.25,...
        0.5,...
        'No reference-condition bins available',...
        'Color','w',...
        'FontSize',14);

    axis off;

end

darkPlot();

exportgraphics(gcf,...
    fullfile(outputFolder,...
    '10_REFERENCE_LOAD_SENSITIVITY.png'),...
    'Resolution',200);

%% ================================================================
% 29. SAVE RESULTS
% ================================================================

RESULTS = struct();

RESULTS.version = 'CMM TTC Final Characterization v1.5';

RESULTS.reference.pressurePsi = REF_PRESSURE_PSI;
RESULTS.reference.pressureKPa = REF_PRESSURE_KPA;
RESULTS.reference.camberDeg = REF_CAMBER_DEG;
RESULTS.reference.speedKph = REF_SPEED_KPH;
RESULTS.reference.FzN = REF_FZ_N;

RESULTS.reference.medianMu = refMedianMu;
RESULTS.reference.meanMu = refMeanMu;
RESULTS.reference.maxMu = refMaxMu;

RESULTS.reference.medianCAlpha = refMedianCA;
RESULTS.reference.medianPeakSA = refMedianPeakSA;
RESULTS.reference.medianPeakFY = refMedianFY;

RESULTS.global.maxMu = globalMu;
RESULTS.global.maxMuPressurePsi = ...
    MASTER.Pressure_psi(idxGlobal);
RESULTS.global.maxMuCamberDeg = ...
    MASTER.Camber_deg(idxGlobal);
RESULTS.global.maxMuFzN = ...
    MASTER.FZ_N(idxGlobal);
RESULTS.global.maxMuFyN = ...
    MASTER.PeakFY_N(idxGlobal);
RESULTS.global.maxMuSADeg = ...
    MASTER.PeakSA_deg(idxGlobal);

RESULTS.lowLoad.medianMu = lowMuMedian;
RESULTS.lowLoad.maxMu = lowMuMax;

RESULTS.symmetry.medianRatio = medianSymmetry;
RESULTS.symmetry.std = symmetryStd;

RESULTS.data.validSamples = height(D);
RESULTS.data.invalidSamples = invalidCount;
RESULTS.data.characterizationRows = height(MASTER);

save(...
    fullfile(outputFolder,...
    'FINAL_TIRE_CHARACTERIZATION_v1_5.mat'),...
    'RESULTS',...
    'MASTER',...
    'ConditionResults');

%% ================================================================
% 30. TEAM REPORT
% ================================================================

reportFile = fullfile(...
    outputFolder,...
    'TEAM_TIRE_CHARACTERIZATION_v1_5.txt');

fid = fopen(reportFile,'w');

fprintf(fid,...
    '============================================================\n');
fprintf(fid,...
    ' CMM TIRE CHARACTERIZATION v1.5\n');
fprintf(fid,...
    '============================================================\n\n');

fprintf(fid,...
    'STATUS: PRE-MF ENGINEERING CHARACTERIZATION\n');
fprintf(fid,...
    'PACEJKA FITTING: NOT PERFORMED\n\n');

fprintf(fid,'TIRE\n');
fprintf(fid,...
    'Hoosier 43075 16x7.5-10 R25B, 7 inch rim\n\n');

fprintf(fid,'TEST MATRIX\n');
fprintf(fid,...
    'Pressure states : 8.11 / 10.09 / 12.10 / 14.11 psi\n');
fprintf(fid,...
    'Camber states   : 0 / +2 / +4 deg\n');
fprintf(fid,...
    'Conditions      : 12\n\n');

fprintf(fid,'REFERENCE CONDITION\n');
fprintf(fid,...
    'Pressure : %.2f psi\n',REF_PRESSURE_PSI);
fprintf(fid,...
    'Camber   : %.2f deg\n',REF_CAMBER_DEG);
fprintf(fid,...
    'Speed    : %.2f kph\n',REF_SPEED_KPH);
fprintf(fid,...
    'FZ       : %.1f N\n\n',REF_FZ_N);

fprintf(fid,'REFERENCE CHARACTERIZATION\n');
fprintf(fid,...
    '------------------------------------------------------------\n');

fprintf(fid,...
    'Median mu_y      : %.4f\n',refMedianMu);

fprintf(fid,...
    'Mean mu_y        : %.4f\n',refMeanMu);

fprintf(fid,...
    'Maximum mu_y     : %.4f\n',refMaxMu);

fprintf(fid,...
    'Median C-alpha   : %.3f N/deg\n',refMedianCA);

fprintf(fid,...
    'Median peak SA   : %.3f deg\n',refMedianPeakSA);

fprintf(fid,...
    'Median peak FY   : %.2f N\n\n',refMedianFY);

fprintf(fid,'GLOBAL LOAD-BINNED RESULT\n');
fprintf(fid,...
    '------------------------------------------------------------\n');

fprintf(fid,...
    'Maximum mu_y : %.4f\n',globalMu);

fprintf(fid,...
    'Pressure     : %.2f psi\n',...
    MASTER.Pressure_psi(idxGlobal));

fprintf(fid,...
    'Camber       : %+5.2f deg\n',...
    MASTER.Camber_deg(idxGlobal));

fprintf(fid,...
    'FZ           : %.2f N\n',...
    MASTER.FZ_N(idxGlobal));

fprintf(fid,...
    'Peak FY      : %.2f N\n',...
    MASTER.PeakFY_N(idxGlobal));

fprintf(fid,...
    'Peak SA      : %.2f deg\n\n',...
    MASTER.PeakSA_deg(idxGlobal));

fprintf(fid,'SYMMETRY\n');
fprintf(fid,...
    '------------------------------------------------------------\n');

fprintf(fid,...
    'Positive/negative median ratio : %.4f\n',...
    medianSymmetry);

fprintf(fid,...
    'Symmetry standard deviation    : %.4f\n\n',...
    symmetryStd);

fprintf(fid,'LOW LOAD\n');
fprintf(fid,...
    '------------------------------------------------------------\n');

fprintf(fid,...
    'Median low-load mu : %.4f\n',lowMuMedian);

fprintf(fid,...
    'Maximum low-load mu: %.4f\n\n',lowMuMax);

fprintf(fid,'ENGINEERING INTERPRETATION\n');
fprintf(fid,...
    '------------------------------------------------------------\n');

fprintf(fid,...
    ['The maximum raw |FY/FZ| value is NOT used as the primary ',...
     'tire friction coefficient.\n']);

fprintf(fid,...
    ['Peak force is evaluated using vertical-load bins to reduce ',...
     'low-load ratio inflation.\n']);

fprintf(fid,...
    ['Pressure and camber states are treated as separate test ',...
     'conditions.\n']);

fprintf(fid,...
    ['Reference-condition statistics are calculated from the ',...
     '12.10 psi / 0 deg condition near the reference load.\n\n']);

fprintf(fid,'MF READINESS\n');
fprintf(fid,...
    '------------------------------------------------------------\n');

fprintf(fid,...
    ['Characterization database generated successfully.\n']);

fprintf(fid,...
    ['Pacejka fitting should begin only after visual review of ',...
     'plots 01-10.\n']);

fclose(fid);

%% ================================================================
% 31. FINAL CONSOLE SUMMARY
% ================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' CMM TTC CHARACTERIZATION v1.5 COMPLETE\n');
fprintf('============================================================\n');

fprintf('\nREFERENCE CONDITION\n');
fprintf('------------------------------------------------------------\n');

fprintf('Pressure        : %.2f psi\n',REF_PRESSURE_PSI);
fprintf('Camber          : %.2f deg\n',REF_CAMBER_DEG);
fprintf('FZ              : %.1f N\n',REF_FZ_N);

fprintf('Median mu_y     : %.4f\n',refMedianMu);
fprintf('Mean mu_y       : %.4f\n',refMeanMu);
fprintf('Maximum mu_y    : %.4f\n',refMaxMu);

fprintf('Median C-alpha  : %.3f N/deg\n',refMedianCA);
fprintf('Median peak SA  : %.3f deg\n',refMedianPeakSA);

fprintf('\nGLOBAL\n');
fprintf('------------------------------------------------------------\n');

fprintf('Maximum binned mu : %.4f\n',globalMu);
fprintf('Pressure          : %.2f psi\n',...
    MASTER.Pressure_psi(idxGlobal));
fprintf('Camber            : %+5.2f deg\n',...
    MASTER.Camber_deg(idxGlobal));
fprintf('FZ                : %.2f N\n',...
    MASTER.FZ_N(idxGlobal));
fprintf('Peak FY           : %.2f N\n',...
    MASTER.PeakFY_N(idxGlobal));
fprintf('Peak SA           : %.2f deg\n',...
    MASTER.PeakSA_deg(idxGlobal));

fprintf('\nSYMMETRY\n');
fprintf('------------------------------------------------------------\n');

fprintf('Median ratio : %.4f\n',medianSymmetry);
fprintf('Std          : %.4f\n',symmetryStd);

fprintf('\nOUTPUT\n');
fprintf('------------------------------------------------------------\n');

fprintf('%s\n',outputFolder);

fprintf('\nMaster CSV:\n%s\n',masterCSV);

fprintf('\nTeam report:\n%s\n',reportFile);

fprintf('\n============================================================\n');
fprintf(' NEXT STEP: ENGINEERING REVIEW -> PACEJKA FIT\n');
fprintf('============================================================\n');